name: Upload Test File to Artifact

on:
  workflow_dispatch:
jobs:
  my_job:
    runs-on: macos-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive file
        run:
          mkfile -n 10m test_file.iso
      
      - name: Upload Test File
        uses: actions/upload-artifact@v4
        with:
          name: test_file.iso
          path: "/Users/runner/work/Download-macOS/Download-macOS/test_file.iso"