name: Upload Test File to Artifact
on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v5
        with:
    	  workflow_search: true
    	  workflow_conclusion: success
    	  branch: upload-test-file-artifact
    	  name: test_file.iso
      
     - name: Archive file
       run: |
         tar -cvzf test_file.tar.gz test_file.iso
         split -b 700k test_file.tar.gz "ISO-archive.part"
      
     - name: Upload to Google Drive A
       uses: logickoder/g-drive-upload@main
       with:
         credentials: ${{ secrets.DRIVE_V2_CREDENTIALS }}
         filename: 'ISO-archive.partaa'
         folderId: ${{ secrets.DRIVE_V2_MACOS_FOLDER_ID }}
         name: 'macOS ${{ env.installer_name }}'
         overwrite: 'true' # optional boolean

     - name: Upload to Google Drive B
       uses: logickoder/g-drive-upload@main
       with:
         credentials: ${{ secrets.DRIVE_CREDENTIALS }}
         filename: 'ISO-archive.partab'
         folderId: ${{ secrets.DRIVE_MACOS_FOLDER_ID }}
         name: 'macOS ${{ env.installer_name }}'
         overwrite: 'true' # optional boolean