name: Send Split file to Drivers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dawidd6/action-download-artifact@v5
        with:
          workflow: generate-installer.yml
          workflow_search: true
          workflow_conclusion: success
          run_id: 9448552974
          skip_unpack: true

      - name: Split File
        run: |
          tar -cvzf ventura.tar.gz 'macOS Ventura'.iso.zip
          split -n 2 ventura.tar.gz "ISO-archive.part"

      - name: Upload to Google Drive A
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.DRIVE_V2_CREDENTIALS }}
          filename: ISO-archive.partaa
          folderId: ${{ secrets.DRIVE_V2_MACOS_FOLDER_ID }}
          name: ISO-archive.partaa
          overwrite: "true"

      - name: Upload to Google Drive B
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: ISO-archive.partab
          folderId: ${{ secrets.DRIVE_MACOS_FOLDER_ID }}
          name: ISO-archive.partab
          overwrite: "true"