name: Test Google Drive Upload File

on:
  workflow_dispatch:

defaults:
      run:
        working-directory: ./scripts
jobs:
  my_job:
    runs-on: macos-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive files
        run:
          mkfile -n 100k test_file		
      
      - name: Upload to Google Drive
        uses: logickoder/g-drive-upload@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: 'test_file'
          folderId: ${{ secrets.DRIVE_MACOS_FOLDER_ID }}
          name: 'macos test file' # optional string
          overwrite: 'true' # optional boolean