name: Upload Test File to Artifact
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v4
      
     - name: Archive file
       run: |
         tar -cvzf test_file.tar.gz test_file.iso
         split -b 700k test_file.tar.gz "ISO-archive.part"
      
     - name: Upload to Google Drive A
       uses: logickoder/g-drive-upload@main
       with:
         credentials: ${{ secrets.DRIVE_V2_CREDENTIALS }}
         filename: 'ISO-archive.partaa'
         folderId: ${{ secrets.DRIVE_V2_MACOS_FOLDER_ID }}
         name: 'ISO-archive.partaa'
         overwrite: 'true' # optional boolean

     - name: Upload to Google Drive B
       uses: logickoder/g-drive-upload@main
       with:
         credentials: ${{ secrets.DRIVE_CREDENTIALS }}
         filename: 'ISO-archive.partab'
         folderId: ${{ secrets.DRIVE_MACOS_FOLDER_ID }}
         name: 'ISO-archive.partab'
         overwrite: 'true' # optional boolean